### ISSUE TITLE
An error is displayed at line 851:data_vel = VN.vtk_to_numpy(array), for the stenosis_NSdata.py. May I ask if there is a lack of data package 'f_5-0'? Looking forward to your answers.  How is this problem solved? I'm getting the same error.

### ISSUE THREAD

**Issue by AKshang** [amir-cardiolab/PINN-wss#7]
An error is displayed at line 851:data_vel = VN.vtk_to_numpy(array), for the stenosis_NSdata.py.
May I ask if there is a lack of data package 'f_5-0'?
Looking forward to your answers.

How is this problem solved? I'm getting the same error.

**Comment by AKshang** [comment]
n_points = data_vtk.GetNumberOfPoints()
print ('n_points of the data file read:' ,n_points)

Besides, n_points is 0,why?

**Comment by amir-cardiolab** [comment]
Hi, f_5-0 is the name of the array in the VTK file you are trying to read. You should open the file in ParaView and see what the name of the array is and place that here. Since you are providing the wrong name for the VTK array then you are getting 0 points (it cannot read anything).
